// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_fRNRzMvFoafS4UE4_1E_TwAaVXO4i_w',
    appId: '1:94359709840:web:0f000fdabf8d7eed93d015',
    messagingSenderId: '94359709840',
    projectId: 'money-df99c',
    authDomain: 'money-df99c.firebaseapp.com',
    storageBucket: 'money-df99c.appspot.com',
    measurementId: 'G-DRWK4X0HJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzKgF7eghdvKh3agMUg0-7q5kSlWuPog',
    appId: '1:94359709840:android:5471e25e9c1c755393d015',
    messagingSenderId: '94359709840',
    projectId: 'money-df99c',
    storageBucket: 'money-df99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9AvKv94KbAzKnEXwXsuuqjd1ORgAolsg',
    appId: '1:94359709840:ios:da9ef97edb1dc44793d015',
    messagingSenderId: '94359709840',
    projectId: 'money-df99c',
    storageBucket: 'money-df99c.appspot.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9AvKv94KbAzKnEXwXsuuqjd1ORgAolsg',
    appId: '1:94359709840:ios:da9ef97edb1dc44793d015',
    messagingSenderId: '94359709840',
    projectId: 'money-df99c',
    storageBucket: 'money-df99c.appspot.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_fRNRzMvFoafS4UE4_1E_TwAaVXO4i_w',
    appId: '1:94359709840:web:67665011cfe24dcc93d015',
    messagingSenderId: '94359709840',
    projectId: 'money-df99c',
    authDomain: 'money-df99c.firebaseapp.com',
    storageBucket: 'money-df99c.appspot.com',
    measurementId: 'G-QFSZW36RXC',
  );
}
